version: 2

models:
    - name: stg_raw__brands
      description: "Product brand names"
      columns:
          - name: brand_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: stg_raw__categories
      description: "Product categories"
      columns:
          - name: category_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    
    - name: stg_raw__customers
      description: "Customers table"
      columns:
          - name: customer_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    
    - name: stg_raw__order_items
      description: "Customers table"
      columns:
          - name: item_id
            description: "The primary key for this table"
            tests: 
              - not_null
          - name: order_id
            description: "The foreign key for this table"
            tests:
                - not_null
    
    - name: stg_raw__orders
      description: "Orders table"
      columns:
          - name: order_id
            description: "The primary key for this table"
            tests: 
              - not_null
              - unique
    
    - name: stg_raw__products
      description: "Products table"
      columns:
          - name: product_id
            description: "The primary key for this table"
            tests: 
              - not_null
              - unique
    
    - name: stg_raw__staffs
      description: "Staffs table"
      columns:
          - name: staff_id
            description: "The primary key for this table"
            tests: 
              - not_null
              - unique
    
    - name: stg_raw__stocks
      description: "Staffs table"
      columns:
          - name: product_id
            description: "The foreign key for this table"
            tests: 
              - not_null
          - name: product_id
            description: "The foreign key for this table"
            tests: 
              - not_null

    - name: stg_raw__stores
      description: "Stores table"
      columns:
          - name: store_id
            description: "The primary key for this table"
            tests: 
              - not_null
              - unique

