3ersion: 2

sources:
  - name: gender_lookups   
    schema: gender_lookups                 
    description: "Tables calculated with python to define gender"
    tables:
      - name: customers_gender
        description: "Customers gender"
      - name: staffs_gender
        description: "Staffs gender"
      
  - name: local_bike_data_lake   
    schema: local_bike_data_lake                 
    description: "Raw data lake tables"
    tables:
      - name: orders
        description: "Orders source table"
      - name: brands
        description: "Brands source table"
      - name: categories
        description: "Categories source table"
      - name: customers
        description: "Customers source table"
      - name: order_items
        description: "Order items source table"
      - name: products
        description: "Products source table"
      - name: staffs
        description: "Staffs source table"
      - name: stocks
        description: "Stocks source table"
      - name: stores
        description: "Stores source table"
